insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('corc usteov', 'Etiam vel augue.', 2, 19, '9/17/2023', '10/2/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('urhr xbglnr', 'In hac habitasse platea dictumst.', 6, 5, '9/15/2023', '12/14/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('hpof rzqiab', 'Nulla mollis molestie lorem. Quisque ut erat.', 6, 4, '2/10/2024', '9/24/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('wymj czzcno', 'Aenean fermentum.', 4, 13, '3/21/2023', '6/4/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ezav mszadx', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 6, 6, '12/26/2023', '7/20/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('rruw quogop', 'Duis mattis egestas metus. Aenean fermentum.', 7, 23, '7/27/2023', '11/6/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('xcsd fusogx', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 6, 11, '12/30/2023', '4/10/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mjxi prsxml', 'Phasellus sit amet erat.', 9, 4, '6/18/2023', '1/9/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('kjrc fzqauv', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 8, 29, '9/10/2023', '4/22/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cetc beexzl', 'Sed vel enim sit amet nunc viverra dapibus.', 6, 17, '3/28/2023', '2/23/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('wtje ukrnwl', 'Aliquam non mauris. Morbi non lectus.', 9, 22, '7/23/2023', '7/18/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('istm jrtgrb', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 3, 23, '10/2/2023', '7/24/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('kjii davnsf', 'In hac habitasse platea dictumst.', 8, 3, '2/25/2024', '3/7/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('eark fnsygl', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4, 6, '7/23/2023', '11/17/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('gcph cfertl', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 2, 27, '7/16/2023', '7/18/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('phjx lwkkfr', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 8, 13, '1/27/2024', '5/22/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('zebl bacvhd', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 3, 5, '3/23/2023', '9/18/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('jksw oveyvp', 'In congue.', 2, 26, '3/31/2023', '4/1/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('gkys lgkzhk', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 5, 13, '9/2/2023', '4/29/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('jzcd dkbvkm', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 8, 12, '10/3/2023', '9/25/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('dqfw hkpmwe', 'Integer a nibh.', 10, 12, '7/19/2023', '4/30/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('shdf actzvp', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 6, 14, '2/18/2024', '1/13/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('zfvr gbldxi', 'Suspendisse potenti. In eleifend quam a odio.', 7, 26, '5/9/2023', '4/25/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('hppm nsqsui', 'Pellentesque ultrices mattis odio.', 10, 23, '7/21/2023', '7/14/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('thdz jbrsqk', 'Donec ut dolor.', 5, 15, '10/11/2023', '7/15/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('zjil xedgdn', 'Aliquam non mauris.', 1, 22, '1/1/2024', '8/29/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('gagi qdfuon', 'Pellentesque at nulla. Suspendisse potenti.', 10, 5, '2/14/2024', '8/17/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('thxo kuntws', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5, 9, '11/29/2023', '5/21/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('uqkc braziz', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 6, 18, '11/23/2023', '4/19/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('tfcm eljgbb', 'Proin eu mi.', 10, 14, '2/6/2024', '12/13/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('yyvb eomawq', 'Morbi a ipsum. Integer a nibh.', 2, 12, '2/1/2024', '8/6/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mfea jhqmzw', 'Maecenas tincidunt lacus at velit.', 7, 4, '4/15/2023', '7/6/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cdnc svltjm', 'Aenean auctor gravida sem.', 2, 11, '2/23/2024', '10/6/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cmkd zifbme', 'Maecenas rhoncus aliquam lacus.', 3, 8, '12/22/2023', '9/15/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('emfh umnzrm', 'Praesent blandit. Nam nulla.', 3, 26, '10/15/2023', '5/23/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('gsyg viujxb', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 6, 6, '10/16/2023', '9/20/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('bmlc vjcrif', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 6, 19, '8/7/2023', '1/5/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mfhx oowywo', 'Integer non velit.', 5, 17, '7/3/2023', '7/22/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('hhwa rsxals', 'Integer tincidunt ante vel ipsum.', 8, 23, '9/24/2023', '2/27/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('lpqm rahwug', 'Morbi a ipsum.', 2, 19, '2/4/2024', '10/18/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('gxah qrzywc', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 4, 14, '6/18/2023', '12/14/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('vyca ozbdbh', 'Donec ut mauris eget massa tempor convallis.', 5, 16, '3/24/2023', '9/21/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('szyg txddnh', 'Nulla mollis molestie lorem. Quisque ut erat.', 3, 7, '6/19/2023', '12/13/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('pelf miqebn', 'Nulla ac enim.', 2, 10, '10/24/2023', '11/11/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('vnfb rspbtj', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 9, 10, '8/17/2023', '1/2/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('lnpz dssznp', 'Suspendisse potenti.', 8, 6, '9/8/2023', '6/25/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('rifj hbxtyi', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 7, 22, '7/12/2023', '8/31/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mivt fixuga', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 3, 18, '8/4/2023', '7/9/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mmvp juahbm', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 9, 15, '1/23/2024', '4/27/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('bglo fpdhpz', 'Nulla mollis molestie lorem.', 2, 20, '7/20/2023', '5/13/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('soyr fmbqkf', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 4, 30, '11/7/2023', '3/17/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ebpx gngluq', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 3, 22, '11/23/2023', '6/24/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cwhd dzmawx', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1, 9, '10/11/2023', '1/30/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('hpzn mssawr', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 1, 7, '7/5/2023', '1/24/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('yjqg wuygsf', 'Suspendisse potenti. Nullam porttitor lacus at turpis.', 3, 20, '2/25/2024', '12/23/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('knkv jylgjt', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 3, 8, '9/12/2023', '7/29/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mzpw bgmtgo', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 2, 30, '10/16/2023', '2/20/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('rqxm fxaswh', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 10, 15, '10/2/2023', '7/18/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('qydx yfggnm', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 4, 11, '12/23/2023', '8/4/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ikkf thwkwm', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 5, 5, '5/24/2023', '11/9/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('athp rdmfgu', 'Etiam faucibus cursus urna. Ut tellus.', 9, 5, '1/27/2024', '7/12/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('izty sosuei', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 8, 26, '5/31/2023', '1/24/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ltlj mlxqbn', 'In quis justo.', 4, 21, '9/27/2023', '8/4/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('egyi uciemw', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 4, 30, '2/5/2024', '10/30/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cqew psrbdb', 'Maecenas tincidunt lacus at velit.', 3, 29, '9/23/2023', '5/20/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cuot cbrhcw', 'Curabitur at ipsum ac tellus semper interdum.', 10, 18, '6/12/2023', '10/31/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('kila ozxivu', 'Vivamus tortor. Duis mattis egestas metus.', 3, 12, '1/1/2024', '12/4/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('lpuy lvxozs', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 3, 28, '1/24/2024', '4/15/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mvbf hwdmri', 'Morbi non quam nec dui luctus rutrum.', 4, 29, '7/9/2023', '6/5/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('zsjy aqktpj', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 8, 5, '7/13/2023', '1/29/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ppym cbajxr', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 1, 19, '4/23/2023', '4/7/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ptbt zwmoyf', 'Nulla tempus.', 6, 19, '9/13/2023', '12/5/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('pmrp ggezmo', 'Proin risus. Praesent lectus.', 5, 16, '6/30/2023', '5/10/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('wwvp lbmpze', 'Nunc nisl.', 1, 27, '3/22/2023', '6/10/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('whfe gzvocp', 'Proin at turpis a pede posuere nonummy.', 8, 13, '6/10/2023', '9/6/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('amul znnhaa', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 6, 4, '6/23/2023', '1/23/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('tbil hfeiad', 'Aenean lectus. Pellentesque eget nunc.', 2, 26, '3/16/2023', '10/19/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mbjf xnziqp', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 8, 9, '4/8/2023', '7/27/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mpvb wpncjb', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 3, 27, '9/20/2023', '4/13/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('mhcu kbbnbe', 'Morbi a ipsum.', 5, 3, '2/2/2024', '8/8/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('qnwx ovsuij', 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 1, '3/17/2023', '5/28/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ucpf gzzpzo', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 6, 16, '7/4/2023', '10/30/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('dmgf dmbzkm', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 8, 21, '12/5/2023', '2/22/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('qvkz htsgmf', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 3, 7, '2/6/2024', '4/18/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('qawv kwexot', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 2, 22, '3/21/2023', '11/2/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('lmcq qtkshd', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 1, 7, '10/1/2023', '11/20/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('feqh juvssy', 'Etiam pretium iaculis justo.', 4, 25, '1/30/2024', '1/25/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('rnrp ntfeyd', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 5, 12, '11/8/2023', '4/13/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('tzmd lvphkh', 'Maecenas rhoncus aliquam lacus.', 6, 1, '7/10/2023', '6/12/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('ngsc zxuneh', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 7, 14, '4/19/2023', '4/9/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('dfdi cbyytp', 'Praesent blandit. Nam nulla.', 9, 10, '12/1/2023', '1/7/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('eomw ajgzmh', 'Nullam porttitor lacus at turpis.', 1, 15, '11/18/2023', '8/5/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('phiv wsamtt', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 9, 5, '1/19/2024', '10/29/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('tduz zduofb', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 5, 2, '1/9/2024', '3/10/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('awns vlzfmb', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3, 30, '7/28/2023', '4/5/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('zswh fcpzad', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 2, 26, '3/17/2023', '1/30/2024');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('hkem yuqmhk', 'Curabitur gravida nisi at nibh.', 7, 7, '4/11/2023', '3/21/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('cqjt itovoj', 'Nulla mollis molestie lorem.', 5, 10, '7/12/2023', '5/21/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('frjo aldjgk', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 9, 27, '2/24/2024', '3/23/2023');
insert into NEWS (header, text, author_id, category_id, create_at, update_at) values ('vcwt btdehm', 'Cras pellentesque volutpat dui.', 9, 27, '12/31/2023', '7/16/2023');
